"""
1. Constants
2. Tuples
3. Parallel lists/tuples
4. Multi Level Lists (tables)
"""

# 🔒 Constants are written in all caps.

SALES_TAX = [
    0.01,
]

days_of_week = (
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
)

states = (
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
)

state_capitals = (
    "Montgomery",
    "Juneau",
    "Phoenix",
    "Little Rock",
    "Sacramento",
    "Denver",
    "Hartford",
    "Dover",
    "Tallahassee",
    "Atlanta",
    "Honolulu",
    "Boise",
    "Springfield",
    "Indianapolis",
    "Des Moines",
    "Topeka",
    "Frankfort",
    "Baton Rouge",
    "Augusta",
    "Annapolis",
    "Boston",
    "Lansing",
    "Saint Paul",
    "Jackson",
    "Jefferson City",
    "Helena",
    "Lincoln",
    "Carson City",
    "Concord",
    "Trenton",
    "Santa Fe",
    "Albany",
    "Raleigh",
    "Bismarck",
    "Columbus",
    "Oklahoma City",
    "Salem",
    "Harrisburg",
    "Providence",
    "Columbia",
    "Pierre",
    "Nashville",
    "Austin",
    "Salt Lake City",
    "Montpelier",
    "Richmond",
    "Olympia",
    "Charleston",
    "Madison",
    "Cheyenne",
)

state_birds = (
    "Yellowhammer",
    "Willow ptarmigan",
    "Cactus wren",
    "Northern mockingbird",
    "California quail",
    "Lark bunting",
    "American robin",
    "Blue hen chicken",
    "Northern mockingbird",
    "Brown thrasher",
    "Hawaiian goose",
    "Mountain bluebird",
    "Northern cardinal",
    "Northern cardinal",
    "Eastern goldfinch",
    "Western meadowlark",
    "Northern cardinal",
    "Brown pelican",
    "Black-capped chickadee",
    "Baltimore oriole",
    "Black-capped chickadee",
    "American robin",
    "Common loon",
    "Northern mockingbird",
    "Eastern bluebird",
    "Western meadowlark",
    "Western meadowlark",
    "Mountain bluebird",
    "Purple finch",
    "Eastern goldfinch",
    "Greater roadrunner",
    "Eastern bluebird",
    "Northern cardinal",
    "Western meadowlark",
    "Northern cardinal",
    "Scissor-tailed flycatcher",
    "Western meadowlark",
    "Ruffed grouse",
    "Rhode Island Red",
    "Carolina wren",
    "Ring-necked pheasant",
    "Northern mockingbird",
    "Northern mockingbird",
    "California gull",
    "Hermit thrush",
    "Northern cardinal",
    "American goldfinch",
    "Northern cardinal",
    "American robin",
    "Western meadowlark",
)

states_and_capitals = (
    ("Alabama", "Montgomery"),
    ("Alaska", "Juneau"),
    ("Arizona", "Phoenix"),
    ("Arkansas", "Little Rock"),
    ("California", "Sacramento"),
    ("Colorado", "Denver"),
    ("Connecticut", "Hartford"),
    ("Delaware", "Dover"),
    ("Florida", "Tallahassee"),
    ("Georgia", "Atlanta"),
    ("Hawaii", "Honolulu"),
    ("Idaho", "Boise"),
    ("Illinois", "Springfield"),
    ("Indiana", "Indianapolis"),
    ("Iowa", "Des Moines"),
    ("Kansas", "Topeka"),
    ("Kentucky", "Frankfort"),
    ("Louisiana", "Baton Rouge"),
    ("Maine", "Augusta"),
    ("Maryland", "Annapolis"),
    ("Massachusetts", "Boston"),
    ("Michigan", "Lansing"),
    ("Minnesota", "Saint Paul"),
    ("Mississippi", "Jackson"),
    ("Missouri", "Jefferson City"),
    ("Montana", "Helena"),
    ("Nebraska", "Lincoln"),
    ("Nevada", "Carson City"),
    ("New Hampshire", "Concord"),
    ("New Jersey", "Trenton"),
    ("New Mexico", "Santa Fe"),
    ("New York", "Albany"),
    ("North Carolina", "Raleigh"),
    ("North Dakota", "Bismarck"),
    ("Ohio", "Columbus"),
    ("Oklahoma", "Oklahoma City"),
    ("Oregon", "Salem"),
    ("Pennsylvania", "Harrisburg"),
    ("Rhode Island", "Providence"),
    ("South Carolina", "Columbia"),
    ("South Dakota", "Pierre"),
    ("Tennessee", "Nashville"),
    ("Texas", "Austin"),
    ("Utah", "Salt Lake City"),
    ("Vermont", "Montpelier"),
    ("Virginia", "Richmond"),
    ("Washington", "Olympia"),
    ("West Virginia", "Charleston"),
    ("Wisconsin", "Madison"),
    ("Wyoming", "Cheyenne"),
)

# 📊 A multi-level tuple can represent a table.
# The outer tuple contains rows; each inner tuple contains one row's columns.
# Each row has three columns: state [0], capital [1], and state bird [2].
states_capitals_birds = (
    ("Alabama", "Montgomery", "Yellowhammer"),
    ("Alaska", "Juneau", "Willow ptarmigan"),
    ("Arizona", "Phoenix", "Cactus wren"),
    ("Arkansas", "Little Rock", "Northern mockingbird"),
    ("California", "Sacramento", "California quail"),
    ("Colorado", "Denver", "Lark bunting"),
    ("Connecticut", "Hartford", "American robin"),
    ("Delaware", "Dover", "Blue hen chicken"),
    ("Florida", "Tallahassee", "Northern mockingbird"),
    ("Georgia", "Atlanta", "Brown thrasher"),
    ("Hawaii", "Honolulu", "Hawaiian goose"),
    ("Idaho", "Boise", "Mountain bluebird"),
    ("Illinois", "Springfield", "Northern cardinal"),
    ("Indiana", "Indianapolis", "Northern cardinal"),
    ("Iowa", "Des Moines", "Eastern goldfinch"),
    ("Kansas", "Topeka", "Western meadowlark"),
    ("Kentucky", "Frankfort", "Northern cardinal"),
    ("Louisiana", "Baton Rouge", "Brown pelican"),
    ("Maine", "Augusta", "Black-capped chickadee"),
    ("Maryland", "Annapolis", "Baltimore oriole"),
    ("Massachusetts", "Boston", "Black-capped chickadee"),
    ("Michigan", "Lansing", "American robin"),
    ("Minnesota", "Saint Paul", "Common loon"),
    ("Mississippi", "Jackson", "Northern mockingbird"),
    ("Missouri", "Jefferson City", "Eastern bluebird"),
    ("Montana", "Helena", "Western meadowlark"),
    ("Nebraska", "Lincoln", "Western meadowlark"),
    ("Nevada", "Carson City", "Mountain bluebird"),
    ("New Hampshire", "Concord", "Purple finch"),
    ("New Jersey", "Trenton", "Eastern goldfinch"),
    ("New Mexico", "Santa Fe", "Greater roadrunner"),
    ("New York", "Albany", "Eastern bluebird"),
    ("North Carolina", "Raleigh", "Northern cardinal"),
    ("North Dakota", "Bismarck", "Western meadowlark"),
    ("Ohio", "Columbus", "Northern cardinal"),
    ("Oklahoma", "Oklahoma City", "Scissor-tailed flycatcher"),
    ("Oregon", "Salem", "Western meadowlark"),
    ("Pennsylvania", "Harrisburg", "Ruffed grouse"),
    ("Rhode Island", "Providence", "Rhode Island Red"),
    ("South Carolina", "Columbia", "Carolina wren"),
    ("South Dakota", "Pierre", "Ring-necked pheasant"),
    ("Tennessee", "Nashville", "Northern mockingbird"),
    ("Texas", "Austin", "Northern mockingbird"),
    ("Utah", "Salt Lake City", "California gull"),
    ("Vermont", "Montpelier", "Hermit thrush"),
    ("Virginia", "Richmond", "Northern cardinal"),
    ("Washington", "Olympia", "American goldfinch"),
    ("West Virginia", "Charleston", "Northern cardinal"),
    ("Wisconsin", "Madison", "American robin"),
    ("Wyoming", "Cheyenne", "Western meadowlark"),
)

# 🔒 Tuples are immutable, so their items cannot be changed after creation.
# 🔎 The first index selects the row; the second index selects the column.
# For example, [0][1] means row 0, column 1: Alabama's capital.
# [row][column] is the general pattern for accessing a table value.
location = states.index("Illinois")
print(location)

# 🖨️ The row index finds Illinois; columns 0 and 1 select its state and capital.
print(
    f"State:  {states_and_capitals[location][0]},  Capital:  {states_and_capitals[location][1]}"
)
